#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive 


[ "$(uname)" == "Linux" ] && sudo apt-get update -y
[ "$(uname)" == "Darwin" ] && brew update

. "${BASEDIR}"/setup-homebrew.sh
[ "$(uname)" == "Darwin" ] && eval "$(/opt/homebrew/bin/brew shellenv)"

which python || ./aptbrew.sh python3

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

if [ "$(uname)" = "Darwin" ]; then
  echo "Run the following command or restart your shell"
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"'
fi

